basic.showIcon(IconNames.TShirt)
basic.forever(function () {
    motor.MotorRun(motor.Motors.M1, motor.Dir.CW, 66)
    basic.pause(500)
    motor.MotorRun(motor.Motors.M2, motor.Dir.CW, 66)
    basic.pause(500)
    motor.MotorRun(motor.Motors.M3, motor.Dir.CW, 66)
    basic.pause(500)
    motor.MotorRun(motor.Motors.M4, motor.Dir.CW, 66)
    basic.pause(1000)
    motor.MotorRun(motor.Motors.M1, motor.Dir.CCW, 94)
    basic.pause(500)
    motor.MotorRun(motor.Motors.M2, motor.Dir.CCW, 133)
    basic.pause(500)
    motor.MotorRun(motor.Motors.M3, motor.Dir.CCW, 104)
    basic.pause(500)
    motor.MotorRun(motor.Motors.M4, motor.Dir.CCW, 106)
    basic.pause(1000)
    motor.motorStopAll()
    basic.pause(1000)
})
